### PR TITLE
pull requests for git assignment

### PR DESCRIPTION
**Pull request by ykm586**
we create a pull requests to merge main branch

### CODE REVIEW

**Comment by yoselita** [comment]
Thank you for sharing this lovely song. I have just one note related to commit messages. They are all the same, but they should be describing the steps you did in each commit. Check In [10] from the lecture, or https://swcarpentry.github.io/git-novice/04-changes/index.html for more details.

**Comment by ykm586** [comment]
hello 

i didn't know that i have to put different message for the different commit , sorry, i have done a mistake.

**Comment by ykm586** [comment]
Hello madam

 I don't know if I clearly understood your question, at the time of the
commit I didn't change the "add New file" information because I didn't know
that i had to put other precise comments at each steps followed

Yvana

Le ven. 18 nov. 2022, 17:13, Josipa Milovac ***@***.***> a
écrit :

**Comment by ykm586** [comment]
Le ven. 18 nov. 2022, 17:13, Josipa Milovac ***@***.***> a
écrit :

**Pull request merged**
